version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/carlpett/stream_exporter
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build
          command: |
            make crossbuild
            make test
            make docker
      - store_artifacts:
          path: binaries
  docker-latest:
    docker:
      - image: circleci/golang:1.12
    steps:
      - run:
          name: Trigger Docker Hub automated build
          command: |
            curl -X POST -H "Content-Type: application/json" \
              --data "{\"docker_tag\": \"latest\"}" \
              https://registry.hub.docker.com/u/carlpett/stream_exporter/trigger/$DOCKER_HUB_TRIGGER_TOKEN/
  release:
    docker:
      - image: circleci/golang:1.12
    working_directory: /go/src/github.com/carlpett/stream_exporter
    steps:
      - checkout
      - run:
          name: Create release
          command: |
            make crossbuild
            make release
      - run:
          name: Trigger Docker Hub automated build
          command: |
            curl -X POST -H "Content-Type: application/json" \
              --data "{\"source_type\": \"Tag\", \"source_name\": \"$CIRCLE_TAG\"}" \
              https://registry.hub.docker.com/u/carlpett/stream_exporter/trigger/$DOCKER_HUB_TRIGGER_TOKEN/
      - store_artifacts:
          path: binaries

workflows:
  version: 2
  build_and_release:
    jobs:
      - build
      - docker-latest:
          filters:
            branches:
              only: master
          requires:
            - build
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
